[project]
name = "study"
version = "1.0.0"
description = "study flask"
dependencies = [
	"flask",
	"email_validator"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"

